version: '3.5'

services:
  
  interactive_short_web:
    image: interactive_short_web
    container_name: interactive_short_web
    build:
      context: web
      dockerfile: Dockerfile
    networks:
      - interactive_short
    ports:
      - 8081:8081
    restart: "always"
  
  interactive_short_server:
    image: interactive_short_server
    container_name: interactive_short_server
    build:
      context: server
      dockerfile: Dockerfile
    networks:
      - interactive_short
    ports:
      - 8082:8082
    restart: "always"
    volumes:
      - './server/assets:/usr/src/app/assets'

networks:
  interactive_short:
    name: interactive_short
    driver: bridge
